### ISSUE TITLE
Unable to build otp 21.0 on OSX 10.13.4

### ISSUE THREAD

**Issue by 7stud** [kerl/kerl#294]
```
~$ kerl version
1.8.3
```

```
~$ which kerl
/usr/local/bin/kerl
```

```
$ kerl build 21.0 21.0

...
...
Verifying archive checksum...
Checksum verified (350988f024f88e9839c3715b35e7e27a)
Extracting source code
Building Erlang/OTP 21.0 (21.0), please wait...
APPLICATIONS DISABLED (See: /Users/7stud/.kerl/builds/21.0/otp_build_21.0.log)
 * odbc           : ODBC library - header check failed

DOCUMENTATION INFORMATION (See: /Users/7stud/.kerl/builds/21.0/otp_build_21.0.log)
 * documentation  : 
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

Build failed.
    WX_GL_MIN_GREEN,       // use green buffer with most bits (> MIN_GREEN bits)
    ^
10 warnings and 3 errors generated.
gmake[3]: *** [Makefile:157: x86_64-apple-darwin17.5.0/wxe_init.o] Error 1
gmake[3]: Leaving directory '/Users/7stud/.kerl/builds/21.0/otp_src_21.0/lib/wx/c_src'
gmake[2]: *** [/Users/7stud/.kerl/builds/21.0/otp_src_21.0/make/otp_subdir.mk:29: opt] Error 2
gmake[2]: Leaving directory '/Users/7stud/.kerl/builds/21.0/otp_src_21.0/lib/wx'
gmake[1]: *** [/Users/7stud/.kerl/builds/21.0/otp_src_21.0/make/otp_subdir.mk:29: opt] Error 2
gmake[1]: Leaving directory '/Users/7stud/.kerl/builds/21.0/otp_src_21.0/lib'
gmake: *** [Makefile:479: libs] Error 2

Please see /Users/7stud/.kerl/builds/21.0/otp_build_21.0.log for full details.
~/.kerl/archives$ 
```

Here's the end of otp_build_21.0.log:
```
...
...
/usr/local/include/wx-3.0/wx/any.h:167:25: note: expanded from macro 'WX_DECLARE_ANY_VALUE_TYPE'
        return wxTypeId(*sm_instance.get()) == wxTypeId(*otherType); \
                        ^
gen/wxe_init.cpp:533:46: error: use of undeclared identifier 'WX_GL_CORE_PROFILE'
 rt.addAtom("WX_GL_CORE_PROFILE"); rt.addInt(WX_GL_CORE_PROFILE);
                                             ^
gen/wxe_init.cpp:575:47: error: use of undeclared identifier 'WX_GL_MAJOR_VERSION'
 rt.addAtom("WX_GL_MAJOR_VERSION"); rt.addInt(WX_GL_MAJOR_VERSION);
                                              ^
gen/wxe_init.cpp:582:47: error: use of undeclared identifier 'WX_GL_MINOR_VERSION'; did you mean 'WX_GL_MIN_GREEN'?
 rt.addAtom("WX_GL_MINOR_VERSION"); rt.addInt(WX_GL_MINOR_VERSION);
                                              ^~~~~~~~~~~~~~~~~~~
                                              WX_GL_MIN_GREEN
/usr/local/include/wx-3.0/wx/glcanvas.h:41:5: note: 'WX_GL_MIN_GREEN' declared here
    WX_GL_MIN_GREEN,       // use green buffer with most bits (> MIN_GREEN bits)
    ^
10 warnings and 3 errors generated.
gmake[3]: *** [Makefile:157: x86_64-apple-darwin17.5.0/wxe_init.o] Error 1
gmake[3]: Leaving directory '/Users/7stud/.kerl/builds/21.0/otp_src_21.0/lib/wx/c_src'
gmake[2]: *** [/Users/7stud/.kerl/builds/21.0/otp_src_21.0/make/otp_subdir.mk:29: opt] Error 2
gmake[2]: Leaving directory '/Users/7stud/.kerl/builds/21.0/otp_src_21.0/lib/wx'
gmake[1]: *** [/Users/7stud/.kerl/builds/21.0/otp_src_21.0/make/otp_subdir.mk:29: opt] Error 2
gmake[1]: Leaving directory '/Users/7stud/.kerl/builds/21.0/otp_src_21.0/lib'
gmake: *** [Makefile:479: libs] Error 2
```

**Comment by fenollp** [comment]
AFAIC 21.0 builds fine on OSX 10.13: https://travis-ci.org/kerl/kerl/builds/407931615

Now at a glance you seem to be having issues related to wxWidgets.

**Comment by mrallen1** [comment]
Yes, if you get that message it means your system literally doesn't have findable wx headers for the compiler to use.

**Comment by mrallen1** [comment]
P.S. Erlang builds perfectly fine without wx.

**Comment by chintan-mishra** [comment]
Yes, Erlang did build as expected. But within `erl` REPL `observer:start().` gave an error.

`wx-config --version` worked fine even before installing WxGTK3-devel and returned the installed version details. It was something like `2.8.10`
