### ISSUE TITLE
R1404 fails to build on Mac OS X 10.8.4

### ISSUE THREAD

**Issue by oubiwann** [kerl/kerl#64]
OS: Mac OS X 10.8.4
```
$ uname -a
Darwin cahwsx01.local 12.4.0 Darwin Kernel Version 12.4.0:\
 Wed May  1 17:57:12 PDT 2013; \
 root:xnu-2050.24.15~1/RELEASE_X86_64 x86_64
```
I tried both of the following, each of which ended in build failure:
```
$ kerl build R14B04 erlang-r14b04 --disable-hipe
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr \
  --with-gxx-include-dir=/usr/include/c++/4.2.1
Verifying archive checksum...
Checksum verified (4b469729f103f52702bfb1fb24529dc0)
Building Erlang/OTP R14B04 (erlang-r14b04), please wait...
Build failed, see \
  /Users/oubiwann/.kerl/builds/erlang-r14b04/otp_build_R14B04.log
```
and
```
$ KERL_CONFIGURE_OPTIONS="--disable-hipe" kerl build R14B04 erlang-r14b04
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr \
  --with-gxx-include-dir=/usr/include/c++/4.2.1
Verifying archive checksum...
Checksum verified (4b469729f103f52702bfb1fb24529dc0)
Building Erlang/OTP R14B04 (erlang-r14b04), please wait...
Build failed, see \
  /Users/oubiwann/.kerl/builds/erlang-r14b04/otp_build_R14B04.log
```
The final error in the log file is this one:
```
Undefined symbols for architecture i386:
  "_bp_sched2ix", referenced from:
      _load_nif_2 in erl_nif.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
(everything prior to that seems to be warnings).

Note that kerl did actually successfully build R13b04...

**Comment by mrallen1** [comment]
PR #18 addresses this same issue for Solaris. Probably should be extended to handle OS X.

**Comment by mrallen1** [comment]
We need to make sure the patch in #18 is the right one for Darwin but if not we can grab it from erlbrew.

**Comment by mrallen1** [comment]
The patch in #18 does not work on OS X. We will have t grab it from erlbrew.

**Comment by fabianmartins** [comment]
This worked pretty well for me
http://verboseguides.com/2016/01/26/installing-erlang-using-kerl/

**Comment by mrallen1** [comment]
#138 should address this issue. Closing. Please reopen if it doesn't work.
